### PR TITLE
fix: change path for embedded postgres

### PR DESCRIPTION
**Pull request by yashmehrotra**
Fixes: #779

### CODE REVIEW

**Review by paddatrapper — APPROVED** [review]
I'm running into a DB error, however this seems to have fixed that particular error. This is after running `operator run --db-migrations`:

```bash
 $ bin/canary-checker topology query fixtures/topology/elastic.yaml --db=embedded://./temp/
INFO[0000] Starting embedded postgres server at ./temp  
The files belonging to this database system will be owned by user "kyle".
This user must also own the server process.

The database cluster will be initialized with locale "en_ZA.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory temp/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Africa/Johannesburg
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    temp/bin/pg_ctl -D temp/data -l logfile start

waiting for server to start....2023-02-13 08:52:16.590 SAST [21187] LOG:  starting PostgreSQL 14.5 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4, 64-bit
2023-02-13 08:52:16.590 SAST [21187] LOG:  listening on IPv6 address "::1", port 6432
2023-02-13 08:52:16.590 SAST [21187] LOG:  listening on IPv4 address "127.0.0.1", port 6432
2023-02-13 08:52:16.631 SAST [21187] LOG:  listening on Unix socket "/tmp/.s.PGSQL.6432"
2023-02-13 08:52:16.633 SAST [21188] LOG:  database system was shut down at 2023-02-13 08:52:16 SAST
2023-02-13 08:52:16.635 SAST [21187] LOG:  database system is ready to accept connections
 done
server started
INFO[0001] Connecting to postgres://postgres:xxxxx@localhost:6432/canary?sslmode=disable 
INFO[0001] Initialized DB: localhost (8497 kB)          
FATA[0001] Failed to query topology: db query failed: ERROR: relation "components" does not exist (SQLSTATE 42P01)

**Comment by yashmehrotra** [comment]
@paddatrapper Might have to add migrations flag in the run query too ? because the error `components` does not exist is because of missing migrations

**Comment by paddatrapper** [comment]
The migrations flag isn't valid for the query command

**Comment by yashmehrotra** [comment]
@moshloop Had a call with @paddatrapper 

Its working as expected, this PR is merge ready

**Pull request merged**
