### PR TITLE
Documentation Overhaul

### PR DESCRIPTION
**Pull request by Joeshiett**
@moshloop I have made the changes to the docs. Do take a look. 
Changes made include:
-    Dark mode
-    Dropdown click option for navigation
-    Tutorial section
-    Check type section
-    Introduction section containing Overview

### CODE REVIEW

**Comment by moshloop** [comment]
@Joeshiett 
- [ ] Remove references to docker, containerd and helm checks
Need to add:
- [ ]  elasticsearch
- [ ] configdb
- [ ] exec
- [ ] mysql
- [ ] gcs database backup
- [ ] kubernetes
- [ ] Need to add examples for SFTP

**Comment by Joeshiett** [comment]
@moshloop I have added some changes. 
Concerning the GCSBucket configuration, it seems there is no check code written for it yet, nor is there an object for GCS in `crd.yaml`. The only one seen so far is the GCS configuration for `folder`, `folder_gcs.go`.

**Comment by moshloop** [comment]
- [ ] Change the TOC
```
Introduction
Tutorial
-- Getting Started
-- Contributing
Installation
-- Kubernetes Operator
-- Standalone Server
-- CLI
Reference
-- Checks
---- Check A 
```
- [ ] Test all links and ensure there are no 404's
- [ ] Add missing checks into the TOC
- [ ] Break down examples into multiple examples
- [ ] Expand description

**Comment by moshloop** [comment]
We are missing TOC entries for many of those checks - Also many of the references to common objects e.g. Template don't work - we probably need
```
Reference
   Checks
   Topology
    Common
```

Please go through and verify all the links are working and all the text is formatted correctly and make sense

**Comment by Joeshiett** [comment]
@moshloop 

Observations:
- There seems to be no reference to `ResourceSelector`, and `JsonCheck` as we have with `Template`, `Connection`, `AWSConnection`, `Bucket`, `FolderFilter`, `GCPConnection`, `Authentication`, `Display`, `VarSource`, `CloudwatchFilter`.
Questions:
- Concerning the document for the Kubernetes Cluster topology, I would like a descriptions for the field: `id`.

**Comment by moshloop** [comment]
@Joeshiett  the config-db tutorial needs to go into the documentation of https://github.com/flanksource/config-db

**Comment by Joeshiett** [comment]
> @Joeshiett the config-db tutorial needs to go into the documentation of https://github.com/flanksource/config-db

 @moshloop concerning the documentation for the config-db, are you referring to the README.md, or I'll have to create a documentation website like the `canary-checker` and will be hosted on Netlify?

**Comment by moshloop** [comment]
@Joeshiett I think lets actually move all of these docs to https://github.com/flanksource/docs

and then update the TOC:

```yaml
Installation
   - Helm Chart

Concepts:
  - Secret Management # e.g. Authentication
  - Templating
  
Checks
   - Install CLI
   - Getting Started
Configuration
    - Install CLI
    - Getting Started
Topology:
    - Getting Started
Reference
    - Checks
    - Configuration
    - Topology
```

**Pull request closed without merging**
